#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2016-2021 ParaPy Holding B.V.
#
# This file is subject to the terms and conditions defined in
# the license agreement that you have received with this source code
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
# PURPOSE.

"""BRepWriter class"""

from OCC.utils.exchange.brep import shape_to_brep_file
from parapy.core import Input, FileWriter
from parapy.geom import Compound
from parapy.geom.occ.drawable import DrawableShape


class BRepWriter(FileWriter):
    """Write one shape :attr:`shape_in` to an .brep file located at
    :attr:`filename`. Usage:

    >>> from parapy.exchange import BRepWriter
    >>> from parapy.geom import Box
    >>> box = Box(1, 2, 3)
    >>> writer = BRepWriter(box, "path/to/your/file.brep")
    >>> writer.write()
    Written: path/to/your/file.brep

    .. note: ParaPy geometry is monkey-patched with a ``write_brep`` method::

        >>> box.write_brep("path/to/your/file.brep")
    """

    __initargs__ = ["shape_in", "filename"]
    file_or_dir = "file"
    wildcard = "BRep files (*.brep,*.BRep,*.BREP) |*.brep;*.BRep;*.BREP"

    #: one shape or a sequence of these
    #: :type: parapy.geom.occ.drawable.DrawableShape | collections.Sequence[parapy.geom.occ.drawable.DrawableShape]
    shape_in = Input()

    def write(self, pathname=None):
        filename = self.resolve_pathname(pathname)
        shape_in = self.shape_in
        if hasattr(type(shape_in), "__iter__"):
            if len(shape_in) > 1:
                shape_in = Compound(shape_in)
            else:
                shape_in = next(iter(shape_in))
        shape_to_brep_file(shape_in.TopoDS_Shape, filename)
        print("Written:", filename)


def _write_brep(self, filename):
    BRepWriter(self, filename).write()

DrawableShape.write_brep = _write_brep


if __name__ == '__main__':
    from parapy.geom import Box
    from parapy.gui import display
    box = Box(1, 2, 3)
    obj = BRepWriter(box)
    display(obj)
    boxes = Box(1, 2, 3), Box(1, 2, 3, position=box.position.translate(x=3))
    obj = BRepWriter(boxes)
    display(obj)
