#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2016-2021 ParaPy Holding B.V.
#
# This file is subject to the terms and conditions defined in
# the license agreement that you have received with this source code
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
# PURPOSE.

import wx

from OCC.gui.viewer import ViewerWindow


def display_topods_shape(topods_shape, *more_shapes):
    app = wx.GetApp() or wx.App(False)
    wx.SafeYield()
    frame = ViewerWindow()
    viewer = frame.viewer
    viewer.display_topods_shape(topods_shape)
    for s in more_shapes:
        viewer.display_topods_shape(s)
    frame.Maximize()
    app.SetTopWindow(frame)
    frame.Raise()
    app.MainLoop()


def display_ais(ais_io, *more_shapes):
    app = wx.GetApp() or wx.App(False)
    wx.SafeYield()
    frame = ViewerWindow()
    viewer = frame.viewer
    viewer.display(ais_io)
    for s in more_shapes:
        viewer.display_topods_shape(s)
    frame.Maximize()
    app.SetTopWindow(frame)
    frame.Raise()
    app.MainLoop()


if __name__ == '__main__':
    from OCC.wrapper.BRepPrimAPI import BRepPrimAPI_MakeBox

    box = BRepPrimAPI_MakeBox(1, 2, 3)
    display_topods_shape(box.Shape())
