#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2016-2021 ParaPy Holding B.V.
#
# This file is subject to the terms and conditions defined in
# the license agreement that you have received with this source code
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
# PURPOSE.

from OCC.wrapper.BRepAdaptor import BRepAdaptor_Surface
from OCC.wrapper.BRepTools import BRepTools__UVBounds


def midpoint_face(topods_face):
    """Usage:

    >>> from OCC.wrapper.BRepPrimAPI import BRepPrimAPI_MakeBox
    >>> builder = BRepPrimAPI_MakeBox(1, 2, 3)
    >>> s = builder.TopFace()
    >>> midpoint_face(s).Coord()
    [0.5, 1.0, 3.0]

    :param topods_face:
    :return:
    """
    adapt = BRepAdaptor_Surface(topods_face)
    u1, u2, v1, v2 = BRepTools__UVBounds(topods_face)
    u = u1 + (u2 - u1) / 2.
    v = v1 + (v2 - v1) / 2.
    return adapt.Value(u, v)

if __name__ == '__main__':
    from OCC.wrapper.BRepPrimAPI import BRepPrimAPI_MakeBox
    builder = BRepPrimAPI_MakeBox(1, 2, 3)
    s = builder.TopFace()
    print(midpoint_face(s).Coord())
